
services:
  postgres:
    image: postgres
    container_name: postgres
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  backend:
    build: ./backend/faalo
    x-develop:
      watch:
        - action: sync
          path: ./backend/faalo
          target: /app
    container_name: nestjs
    restart: always
    depends_on:
      - postgres
    env_file:
      - ./backend/faalo/.env
    ports:
      - "3000:3000"
    volumes:
      - ./backend/faalo:/app
      - /app/node_modules 
    command: >
      sh -c "npm run start:dev"
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
